### ISSUE TITLE
Building loop_tool with loop_nest on apple M1 

### ISSUE THREAD

**Issue by dejangrubisic** [loopstack/loop_tune#1]
We want to use LoopTool environment with a fast LoopNest backend for CompilerGym. 

### Environments

1. Conda compiler_gym python=3.8

> **compiler_gym**
> Successfully builds and runs

> **loop_tool**
> Can’t find boost library necessary for LoopNest
> Compiles and runs with lt.Backend("loop_nest"):
> when we add code to CMakeLists.txt, but 
> if (BUILD_LOOP_NEST) <<<<<<<<<<<<<<<< original
>  find_package(Boost 1.66.0) <<<<<<<<<<< added code
>  if(Boost_FOUND)
>    include_directories(${Boost_INCLUDE_DIRS})
>  else()
>    message(FATAL_ERROR "Can't find boost libraries")
>  endif()
>  list(APPEND CORE_SRCS "${SRC_DIR}/backends/cpu/loop_nest.cpp") <<<<<<<<<<<< original
> LoopTool.ui doesn’t work (returns Illegal instruction: 4)
> with lt.Backend("loop_nest"): works as long you don’t run the code

2. Conda native_arm python=3.8

> **compiler_gym** 
> pip can’t find it
> ERROR: Could not find a version that satisfies the requirement compiler_gym (from versions: none)

> **loop_tool**
> Successfully works with LoopNest

3. Venv

> **compiler_gym**
> pip can’t find it

> **loop_tool**
> with lt.Backend(“loop_nest”) fails with 
> NameError: name 'get_default_backend' is not defined

### Building

**1. Conda native_arm python=3.8**
How to specify the architecture or platform for a new conda environment? (Apple Silicon)

```
> CONDA_SUBDIR=osx-arm64 conda create -n native py38_native -c conda-forge 
> conda activate py38_native
> conda config --env --set subdir osx-arm64
```

**2. Venv**

```
brew install python@3.8
python3 -m venv pyenv38
source path_to/pyenv38/bin/activate
```

**Comment by bwasti** [comment]
I think we'll need to build compiler gym from source for this to work.  (compiler gym only has x86_64 Mac OS available for pip: https://pypi.org/simple/compiler-gym/)

Here's what I've got so far:
```
brew tap bazelbuild/tap
brew extract bazel bazelbuild/tap --version 4.2.2
brew install bazel@4.2.2
```
^ this took 15 minutes to build lol

Then you'll need to patch compiler gym to install things on M1 (skipping TF, DGL and exporting a variable for gpcro
Patch file: https://jott.live/code/compiler_gym.patch

```
cd CompilerGym/
curl https://jott.live/raw/compiler_gym.patch > compiler_gym.patch
git apply compiler_gym.patch
```

At this point you can run
```
make init
make install
```
